<a href="https://colab.research.google.com/github/lhg96/-AI-RSSCrawler/blob/main/6_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%A7%80%EB%8F%84%ED%95%99%EC%8A%B5_%EB%B6%84%EB%A5%98_AutoML%EC%9D%84_%EC%9D%B4%EC%9A%A9%ED%95%9C_%EC%B5%9C%EC%A0%81%EB%AA%A8%EB%8D%B8_%EC%84%A0%EC%A0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# AutoML

- 데이터 수집/분석-EDA등을 제외한 전 공정을 AutoML로 진행 가능함
- 파이캐럿 사용

# 설치

In [ ]:
!pip install pycaret[full]
# 세션 다시 시작 메세지 발생 -> 다시 시작 클릭
!pip install -U jinja2      # 템플릿엔진(웹에서 사용하는)

Collecting pycaret[full]
  Downloading pycaret-3.3.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: ipython>=5.5.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (7.34.0)
Requirement already satisfied: ipywidgets>=7.6.5 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (7.7.1)
Requirement already satisfied: tqdm>=4.62.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (4.67.1)
Collecting numpy<1.27,>=1.21 (from pycaret[full])
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.4 MB/s eta 0:00:00
Collecting pandas<2.2.0 (from pycaret[full])
  Downloading pandas-2.1.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: jinja2>=3 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (3.1.6)
Collecting scipy<=1.11.4,>=1.6.1 (from pycaret[full])
  Downloading scipy-1.11.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 2.9 MB/s eta 0:00:00
Collecting joblib<1.4,>=1.2.0 (from pycaret[full])
  Downloading joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: scikit-learn>1.4.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (1.6.1)
Collecting pyod>=1.1.3 (from pycaret[full])
  Downloading pyod-2.0.5-py3-none-any.whl.metadata (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.3/46.3 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: imbalanced-learn>=0.12.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (0.13.0)
Collecting category-encoders>=2.4.0 (from pycaret[full])
  Downloading category_encoders-2.8.1-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: lightgbm>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (4.5.0)
Requirement already satisfied: numba>=0.55.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (0.60.0)
Requirement already satisfied: requests>=2.27.1 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (2.32.3)
Requirement already satisfied: psutil>=5.9.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (5.9.5)
Requirement already satisfied: markupsafe>=2.0.1 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (3.0.2)
Requirement already satisfied: importlib-metadata>=4.12.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (8.7.0)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (5.10.4)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (3.1.1)
Collecting deprecation>=2.1.0 (from pycaret[full])
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (3.5.0)
Collecting matplotlib<3.8.0 (from pycaret[full])
  Downloading matplotlib-3.7.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.7 kB)
Collecting scikit-plot>=0.3.7 (from pycaret[full])
  Downloading scikit_plot-0.3.7-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: yellowbrick>=1.4 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (1.5)
Requirement already satisfied: plotly>=5.14.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (5.24.1)
Collecting kaleido>=0.2.1 (from pycaret[full])
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl.metadata (15 kB)
Collecting schemdraw==0.15 (from pycaret[full])
  Downloading schemdraw-0.15-py3-none-any.whl.metadata (2.2 kB)
Collecting plotly-resampler>=0.8.3.1 (from pycaret[full])
  Downloading plotly_resampler-0.10.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: statsmodels>=0.12.1 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (0.14.4)
Collecting sktime==0.26.0 (from pycaret[full])
  Downloading sktime-0.26.0-py3-none-any.whl.metadata (29 kB)
Collecting tbats>=1.1.3 (from pycaret[full])
  Downloading tbats-1.1.3-py3-none-any.whl.metadata (3.8 kB)
Collecting pmdarima>=2.0.4 (from pycaret[full])
  Downloading pmdarima-2.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: wurlitzer in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (3.1.1)
Collecting shap~=0.44.0 (from pycaret[full])
  Downloading shap-0.44.1-cp311-cp311-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (24 kB)
Collecting interpret>=0.2.7 (from pycaret[full])
  Downloading interpret-0.6.10-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: umap-learn>=0.5.2 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (0.5.7)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (6.0.2)
Collecting ydata-profiling>=4.3.1 (from pycaret[full])
  Downloading ydata_profiling-4.16.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting explainerdashboard>=0.3.8 (from pycaret[full])
  Downloading explainerdashboard-0.4.8-py3-none-any.whl.metadata (3.8 kB)
Collecting fairlearn==0.7.0 (from pycaret[full])
  Downloading fairlearn-0.7.0-py3-none-any.whl.metadata (7.3 kB)
Collecting kmodes>=0.11.1 (from pycaret[full])
  Downloading kmodes-0.12.2-py2.py3-none-any.whl.metadata (8.1 kB)
Requirement already satisfied: mlxtend>=0.19.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (0.23.4)
Collecting statsforecast<1.6.0,>=0.5.5 (from pycaret[full])
  Downloading statsforecast-1.5.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: hyperopt>=0.2.7 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (0.2.7)
Collecting optuna>=3.0.0 (from pycaret[full])
  Downloading optuna-4.3.0-py3-none-any.whl.metadata (17 kB)
Collecting optuna-integration (from pycaret[full])
  Downloading optuna_integration-4.3.0-py3-none-any.whl.metadata (12 kB)
Collecting scikit-optimize>=0.9.0 (from pycaret[full])
  Downloading scikit_optimize-0.10.2-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting mlflow>=2.0.0 (from pycaret[full])
  Downloading mlflow-2.22.0-py3-none-any.whl.metadata (30 kB)
Collecting gradio>=3.50.2 (from pycaret[full])
  Downloading gradio-5.32.0-py3-none-any.whl.metadata (16 kB)
Collecting boto3>=1.24.56 (from pycaret[full])
  Downloading boto3-1.38.27-py3-none-any.whl.metadata (6.6 kB)
Collecting fastapi (from pycaret[full])
  Downloading fastapi-0.115.12-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn>=0.17.6 (from pycaret[full])
  Downloading uvicorn-0.34.2-py3-none-any.whl.metadata (6.5 kB)
Collecting m2cgen>=0.9.0 (from pycaret[full])
  Downloading m2cgen-0.10.0-py3-none-any.whl.metadata (9.9 kB)
Collecting evidently~=0.4.16 (from pycaret[full])
  Downloading evidently-0.4.40-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: dask>=2024.4.1 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (2024.12.1)
Requirement already satisfied: distributed>=2024.4.1 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (2024.12.1)
Collecting fugue~=0.8.0 (from pycaret[full])
  Downloading fugue-0.8.7-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: flask in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (3.1.1)
Collecting Werkzeug<3.0,>=2.2 (from pycaret[full])
  Downloading werkzeug-2.3.8-py3-none-any.whl.metadata (4.1 kB)
Collecting pytest<8.0.0 (from pycaret[full])
  Downloading pytest-7.4.4-py3-none-any.whl.metadata (7.9 kB)
Collecting moto<5.0.0 (from pycaret[full])
  Downloading moto-4.2.14-py2.py3-none-any.whl.metadata (12 kB)
Collecting dash[testing] (from pycaret[full])
  Downloading dash-3.0.4-py3-none-any.whl.metadata (10 kB)
Collecting scikit-learn-intelex>=2023.0.1 (from pycaret[full])
  Downloading scikit_learn_intelex-2025.5.0-py311-none-manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting catboost>=0.23.2 (from pycaret[full])
  Downloading catboost-1.2.8-cp311-cp311-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: xgboost>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from pycaret[full]) (2.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from sktime==0.26.0->pycaret[full]) (24.2)
Collecting scikit-base<0.8.0 (from sktime==0.26.0->pycaret[full])
  Downloading scikit_base-0.7.8-py3-none-any.whl.metadata (8.8 kB)
Collecting scikit-learn>1.4.0 (from pycaret[full])
  Downloading scikit_learn-1.4.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting botocore<1.39.0,>=1.38.27 (from boto3>=1.24.56->pycaret[full])
  Downloading botocore-1.38.27-py3-none-any.whl.metadata (5.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.24.56->pycaret[full])
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.14.0,>=0.13.0 (from boto3>=1.24.56->pycaret[full])
  Downloading s3transfer-0.13.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.11/dist-packages (from catboost>=0.23.2->pycaret[full]) (0.20.3)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from catboost>=0.23.2->pycaret[full]) (1.17.0)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.11/dist-packages (from category-encoders>=2.4.0->pycaret[full]) (1.0.1)
INFO: pip is looking at multiple versions of category-encoders to determine which version is compatible with other requirements. This could take a while.
Collecting category-encoders>=2.4.0 (from pycaret[full])
  Downloading category_encoders-2.8.0-py3-none-any.whl.metadata (7.9 kB)
  Downloading category_encoders-2.7.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.11/dist-packages (from dask>=2024.4.1->pycaret[full]) (8.2.1)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2024.4.1->pycaret[full]) (2025.3.2)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2024.4.1->pycaret[full]) (1.4.2)
Requirement already satisfied: toolz>=0.10.0 in /usr/local/lib/python3.11/dist-packages (from dask>=2024.4.1->pycaret[full]) (0.12.1)
Requirement already satisfied: locket>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from distributed>=2024.4.1->pycaret[full]) (1.0.0)
Requirement already satisfied: msgpack>=1.0.2 in /usr/local/lib/python3.11/dist-packages (from distributed>=2024.4.1->pycaret[full]) (1.1.0)
Requirement already satisfied: sortedcontainers>=2.0.5 in /usr/local/lib/python3.11/dist-packages (from distributed>=2024.4.1->pycaret[full]) (2.4.0)
Requirement already satisfied: tblib>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from distributed>=2024.4.1->pycaret[full]) (3.1.0)
Requirement already satisfied: tornado>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from distributed>=2024.4.1->pycaret[full]) (6.4.2)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.11/dist-packages (from distributed>=2024.4.1->pycaret[full]) (2.4.0)
Requirement already satisfied: zict>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from distributed>=2024.4.1->pycaret[full]) (3.0.0)
Requirement already satisfied: nltk>=3.6.7 in /usr/local/lib/python3.11/dist-packages (from evidently~=0.4.16->pycaret[full]) (3.9.1)
Requirement already satisfied: pydantic>=1.10.13 in /usr/local/lib/python3.11/dist-packages (from evidently~=0.4.16->pycaret[full]) (2.11.4)
Collecting litestar>=2.8.3 (from evidently~=0.4.16->pycaret[full])
  Downloading litestar-2.16.0-py3-none-any.whl.metadata (110 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.0/111.0 kB 2.9 MB/s eta 0:00:00
Collecting typing-inspect>=0.9.0 (from evidently~=0.4.16->pycaret[full])
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting watchdog>=3.0.0 (from evidently~=0.4.16->pycaret[full])
  Downloading watchdog-6.0.0-py3-none-manylinux2014_x86_64.whl.metadata (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.3/44.3 kB 1.7 MB/s eta 0:00:00
Requirement already satisfied: typer>=0.3 in /usr/local/lib/python3.11/dist-packages (from evidently~=0.4.16->pycaret[full]) (0.15.3)
Requirement already satisfied: rich>=13 in /usr/local/lib/python3.11/dist-packages (from evidently~=0.4.16->pycaret[full]) (13.9.4)
Collecting iterative-telemetry>=0.0.5 (from evidently~=0.4.16->pycaret[full])
  Downloading iterative_telemetry-0.0.10-py3-none-any.whl.metadata (4.1 kB)
Collecting dynaconf>=3.2.4 (from evidently~=0.4.16->pycaret[full])
  Downloading dynaconf-3.2.11-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: certifi>=2024.7.4 in /usr/local/lib/python3.11/dist-packages (from evidently~=0.4.16->pycaret[full]) (2025.4.26)
Collecting ujson>=5.4.0 (from evidently~=0.4.16->pycaret[full])
  Downloading ujson-5.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.3 kB)
Collecting uuid6>=2024.7.10 (from evidently~=0.4.16->pycaret[full])
  Downloading uuid6-2024.7.10-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: cryptography>=43.0.1 in /usr/local/lib/python3.11/dist-packages (from evidently~=0.4.16->pycaret[full]) (43.0.3)
Collecting dash-auth (from explainerdashboard>=0.3.8->pycaret[full])
  Downloading dash_auth-2.3.0-py3-none-any.whl.metadata (10 kB)
Collecting dash-bootstrap-components>=1 (from explainerdashboard>=0.3.8->pycaret[full])
  Downloading dash_bootstrap_components-2.0.3-py3-none-any.whl.metadata (18 kB)
Collecting dtreeviz>=2.1 (from explainerdashboard>=0.3.8->pycaret[full])
  Downloading dtreeviz-2.2.2-py3-none-any.whl.metadata (2.4 kB)
Collecting flask_simplelogin (from explainerdashboard>=0.3.8->pycaret[full])
  Downloading flask_simplelogin-0.2.0-py3-none-any.whl.metadata (3.3 kB)
Collecting Flask-WTF>=1.1 (from explainerdashboard>=0.3.8->pycaret[full])
  Downloading flask_wtf-1.2.2-py3-none-any.whl.metadata (3.4 kB)
Collecting jupyter_dash>=0.4.1 (from explainerdashboard>=0.3.8->pycaret[full])
  Downloading jupyter_dash-0.4.2-py3-none-any.whl.metadata (3.6 kB)
Collecting oyaml (from explainerdashboard>=0.3.8->pycaret[full])
  Downloading oyaml-1.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting waitress (from explainerdashboard>=0.3.8->pycaret[full])
  Downloading waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Collecting triad>=0.9.3 (from fugue~=0.8.0->pycaret[full])
  Downloading triad-0.9.8-py3-none-any.whl.metadata (6.3 kB)
Collecting adagio>=0.2.4 (from fugue~=0.8.0->pycaret[full])
  Downloading adagio-0.2.6-py3-none-any.whl.metadata (1.8 kB)
Collecting qpd>=0.4.4 (from fugue~=0.8.0->pycaret[full])
  Downloading qpd-0.4.4-py3-none-any.whl.metadata (6.4 kB)
Collecting fugue-sql-antlr>=0.1.6 (from fugue~=0.8.0->pycaret[full])
  Downloading fugue-sql-antlr-0.2.2.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 11.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: sqlglot in /usr/local/lib/python3.11/dist-packages (from fugue~=0.8.0->pycaret[full]) (25.20.2)
Collecting aiofiles<25.0,>=22.0 (from gradio>=3.50.2->pycaret[full])
  Downloading aiofiles-24.1.0-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio>=3.50.2->pycaret[full]) (4.9.0)
Collecting ffmpy (from gradio>=3.50.2->pycaret[full])
  Downloading ffmpy-0.5.0-py3-none-any.whl.metadata (3.0 kB)
Collecting gradio-client==1.10.2 (from gradio>=3.50.2->pycaret[full])
  Downloading gradio_client-1.10.2-py3-none-any.whl.metadata (7.1 kB)
Collecting groovy~=0.1 (from gradio>=3.50.2->pycaret[full])
  Downloading groovy-0.1.2-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.11/dist-packages (from gradio>=3.50.2->pycaret[full]) (0.28.1)
Requirement already satisfied: huggingface-hub>=0.28.1 in /usr/local/lib/python3.11/dist-packages (from gradio>=3.50.2->pycaret[full]) (0.31.4)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.11/dist-packages (from gradio>=3.50.2->pycaret[full]) (3.10.18)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.11/dist-packages (from gradio>=3.50.2->pycaret[full]) (11.2.1)
Collecting pydub (from gradio>=3.50.2->pycaret[full])
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart>=0.0.18 (from gradio>=3.50.2->pycaret[full])
  Downloading python_multipart-0.0.20-py3-none-any.whl.metadata (1.8 kB)
Collecting ruff>=0.9.3 (from gradio>=3.50.2->pycaret[full])
  Downloading ruff-0.11.12-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting safehttpx<0.2.0,>=0.1.6 (from gradio>=3.50.2->pycaret[full])
  Downloading safehttpx-0.1.6-py3-none-any.whl.metadata (4.2 kB)
Collecting semantic-version~=2.0 (from gradio>=3.50.2->pycaret[full])
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Collecting starlette<1.0,>=0.40.0 (from gradio>=3.50.2->pycaret[full])
  Downloading starlette-0.47.0-py3-none-any.whl.metadata (6.2 kB)
Collecting tomlkit<0.14.0,>=0.12.0 (from gradio>=3.50.2->pycaret[full])
  Downloading tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.11/dist-packages (from gradio>=3.50.2->pycaret[full]) (4.13.2)
Requirement already satisfied: websockets<16.0,>=10.0 in /usr/local/lib/python3.11/dist-packages (from gradio-client==1.10.2->gradio>=3.50.2->pycaret[full]) (15.0.1)
Collecting starlette<1.0,>=0.40.0 (from gradio>=3.50.2->pycaret[full])
  Downloading starlette-0.46.2-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: networkx>=2.2 in /usr/local/lib/python3.11/dist-packages (from hyperopt>=0.2.7->pycaret[full]) (3.4.2)
Requirement already satisfied: future in /usr/local/lib/python3.11/dist-packages (from hyperopt>=0.2.7->pycaret[full]) (1.0.0)
Requirement already satisfied: py4j in /usr/local/lib/python3.11/dist-packages (from hyperopt>=0.2.7->pycaret[full]) (0.10.9.7)
Requirement already satisfied: sklearn-compat<1,>=0.1 in /usr/local/lib/python3.11/dist-packages (from imbalanced-learn>=0.12.0->pycaret[full]) (0.1.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from imbalanced-learn>=0.12.0->pycaret[full]) (3.6.0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata>=4.12.0->pycaret[full]) (3.21.0)
Collecting interpret-core==0.6.10 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.6.10->interpret>=0.2.7->pycaret[full])
  Downloading interpret_core-0.6.10-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: ipykernel>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.6.10->interpret>=0.2.7->pycaret[full]) (6.17.1)
Collecting SALib>=1.3.3 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.6.10->interpret>=0.2.7->pycaret[full])
  Downloading salib-1.5.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: dill>=0.2.5 in /usr/local/lib/python3.11/dist-packages (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.6.10->interpret>=0.2.7->pycaret[full]) (0.3.7)
Collecting aplr>=10.6.1 (from interpret-core[aplr,dash,debug,linear,notebook,plotly,sensitivity,shap]==0.6.10->interpret>=0.2.7->pycaret[full])
  Downloading aplr-10.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.4 kB)

Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (3.1.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2) (3.0.2)

In [ ]:
import pycaret

In [ ]:
# 써드 파트 알고리즘 설치
!pip install catboost -q

# 베이스라인 구축(간단하게)

- 데이터
  - load_breast_cancer()
- 알고리즘
  - 랜덤포레스트
- 데이터
  - 9:1 분할 (소량의 데이터에서 훈련량을 높이는 방향성)
  - 난수 시드 사용
  - 층화 x
- 평가
  - 정확도

In [ ]:
# 1. 알고리즘 선택
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

# 2. 데이터 준비및 분할
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()

# 파이캐럿 사용시 편의성 고려하여 df로 구성함
import pandas as pd
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target # 정답 데이터 추가
df.head(2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.8,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.9,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.8,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0

In [ ]:
df.shape

(569, 31)

In [ ]:

# 피처 데이터만 추출 => df.iloc[ 1차원 (행) , 2차원 (열) ] => 데이터프레임의 데이터 추출방법
# : => 처음부터 끝까지
# :-1 => 처음부터 마지막 1개를 제외한 나머지 모두=
df.iloc[ : , :-1 ]

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,25.380,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,24.990,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,23.570,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,14.910,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,22.540,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,25.450,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,23.690,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,18.980,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,25.740,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,9.456,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039

- 데이터 추출법
  - 적용 자료구조
    - 문자열, 리스트, 튜플, 딕셔너리, 배열(넘파이), 시리즈, 데이터프레임(분석, 머신러닝, 딥러닝), 텐서(딥러닝)
  - 인덱싱
    - 차원 축소, 데이터 특정한다(인덱스)
  - 슬라이싱
    - 차원 유지, 데이터를 자른다(연속적, 이웃한 데이터)

  - 인덱스
    - 정방향 => 0, 1, 2, .. 앞에서부터 체크
    - 역방향 => -1, -2, -3, ... 뒤에서부터 체크

In [ ]:
# 정답 데이터만 추출 => Series로 출력됨(1차원)
# : => 처음부터 끝까지
# -1 => 역방향 인덱스 마지막 컬럼 1개만 특정 => 차원축소
df.iloc[ : , -1 ] # 모든 데이터에 정답(컬럼명 target)을 추출하시오

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: target, Length: 569, dtype: int64

In [ ]:
# 데이터 분할 처리 (9:1)
from sklearn.model_selection import train_test_split

# 피처 데이터 (정답 제외한 나머지 모든 데이터만 추출하시오)
X = df.iloc[ : , :-1 ] # 1차원 데이터는 모두 가져온다, 2차원데이터는 마지막 1개만 제외
# 정답 데이터
y = df.iloc[ : , -1 ] # 1차원 데이터는 모두 가져온다, 2차원 데이터는 정답만(마지막 1개만)추출

# 데이터 분할 처리, 9:1
X_train, X_test, y_train, y_test = train_test_split(X,y,
                                   test_size=0.1, random_state=42)

In [ ]:
# 3. 훈련
model.fit( X_train, y_train )

# 4. 예측및 평가
from sklearn.metrics import accuracy_score

# 예측
y_pred = model.predict( X_test )
# 정답, 예측값을 넣어서 정확도 평가
accuracy_score( y_test, y_pred )

0.9649122807017544

- 결론
  - 프로토타입으로 베이스라인 구축을 통해 96.4%까지 진입

- 목표
  - AutoML이용하여 98%대까지 모델 성능 향상(교체)

# AutoML 적용 - 자동

### 데이터 준비

In [ ]:
# 1. 필요한 분류-모듈 모두 가져오기
from pycaret.classification import *

In [ ]:

# 2. 분할된 훈련용 데이터 (피처, 정답)를 하나로 합치기 => 파이캐럿에 넣기 위해서 구성
#   axis : 0이면 수직으로 병합(데이터가 늘어남), 1이면 수평으로 병합(컬럼 추가, 피처나 정답 데이터 추가)
# pandas의 concat() 함수는 데이터 단순 합치지기 함수
X = pd.concat( [X_train, y_train], axis=1 ) # 데이터의 수는 유지, 컬럼 확장
X.head(2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
82,25.22,24.91,171.5,1878.0,0.1063,0.2665,0.3339,0.18450,0.1829,0.06782,...,33.62,211.7,2562.0,0.1573,0.6076,0.6476,0.2867,0.2355,0.1051,0
39,13.48,20.82,88.4,559.2,0.1016,0.1255,0.1063,0.05439,0.1720,0.06419,...,26.02,107.3,740.4,0.1610,0.4225,0.5030,0.2258,0.2807,0.1071,0

In [ ]:
# 데이터 512개, 31(피처 30개, 정답 1개)
X.shape

(512, 31)

### steup()
  - 피처 엔지니어링을 automl에 맡겨서 진행
    - 설정된 범위안에서만 작동
  - 직관적으로 피처 엔지니어링을 진행후 automl 진행 가능함.
    - automl은 알고리즘 및 파이프라인에만 집중되게 사용

In [ ]:
# 분류기 생성
# 파이캐럿의 setup() : automl 학습을 위한 설정(훈련데이터, 다양한 옵션설정)
clf = setup(
  data   = X,        # 피처 + 정답이 포함된 데이터, DataFrame
  target = 'target', # target 컬럼이 정답이다 => 컬럼명 지정
  verbose= True,     # 로그 출력
  # 데이터가 적어서 9:1로 설정
  train_size= 0.9,   # 훈련:검증 = 9:1 => 교차검증(cv) 수행하겠다 => 모델 과대/과소 체크,
  data_split_shuffle= True, # 데이터를 분할할때 섞겠다
  session_id= 100,   # 난수 시드
  normalize = True,  # 데이터에 대한 정규화 처리 진행(데이터를 조정하겠다) => 데이터의 스케일 조정
)

In [ ]:
# 후보 알고리즘
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
catboost,CatBoost Classifier,catboost.core.CatBoostClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

### compare_models(), 후보 모델 획득

In [ ]:
# 최적 후보 상위 탑 5 획득
'''
- fold : 교차 검증은 5세트만 진행
- round : 교차 검증은 완료하는 라운드를 3번 진행
- sort : 상위 탑 5를 선택할대는 정확도를 기준으로 선정
- n_select : 상위 랭커 5개만 선정
'''
top_5 =  compare_models( fold=5, round=3, sort='Accuracy', n_select=5 )

Processing:   0%|          | 0/73 [00:00<?, ?it/s]

In [ ]:
# 상위 5개 모델 확인
# 상위 5개 모델 추출, 각 모델(알고리즘)별 (하이퍼) 파라미터 최적값 확인
top_5

[LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                    intercept_scaling=1, l1_ratio=None, max_iter=1000,
                    multi_class='auto', n_jobs=None, penalty='l2',
                    random_state=100, solver='lbfgs', tol=0.0001, verbose=0,
                    warm_start=False),
 ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                      criterion='gini', max_depth=None, max_features='sqrt',
                      max_leaf_nodes=None, max_samples=None,
                      min_impurity_decrease=0.0, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      monotonic_cst=None, n_estimators=100, n_jobs=-1,
                      oob_score=False, random_state=100, verbose=0,
                      warm_start=False),
 <catboost.core.CatBoostClassifier at 0x7d626b564110>,
 KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                      metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                      weights='uniform'),
 RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                        criterion='gini', max_depth=None, max_features='sqrt',
                        max_leaf_nodes=None, max_samples=None,
                        min_impurity_decrease=0.0, min_samples_leaf=1,
                        min_samples_split=2, min_weight_fraction_leaf=0.0,
                        monotonic_cst=None, n_estimators=100, n_jobs=-1,
                        oob_score=False, random_state=100, verbose=0,
                        warm_start=False)]

### blend_models() : 블랜딩 - 보팅
  - 여러 알고리즘을 섞어서 모델 구성
  - 앙상블 보팅 전략
    - 하드보팅(다수결), 소프트보팅(점유율, 총합으로결정)

In [ ]:
blended = blend_models( estimator_list = top_5,
              fold = 10, # cv 세트값, 하이퍼 파라미터값을 가지고 다시 진행한다는 의미
              optimize = 'Accuracy', # 최적화할 지표
              method = 'soft' # 소프트보팅
              )

Processing:   0%|          | 0/6 [00:00<?, ?it/s]

### finalize_model() : 최적 모델 추출

In [ ]:
model = finalize_model(blended)

In [ ]:
model

Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['mean radius', 'mean texture',
                                             'mean perimeter', 'mean area',
                                             'mean smoothness',
                                             'mean compactness',
                                             'mean concavity',
                                             'mean concave points',
                                             'mean symmetry',
                                             'mean fractal dimension',
                                             'radius error', 'texture error',
                                             'perimeter error', 'area error',
                                             'smoothness error',
                                             'com...
                                                                      max_features='sqrt',
                                                                      max_leaf_nodes=None,
                                                                      max_samples=None,
                                                                      min_impurity_decrease=0.0,
                                                                      min_samples_leaf=1,
                                                                      min_samples_split=2,
                                                                      min_weight_fraction_leaf=0.0,
                                                                      monotonic_cst=None,
                                                                      n_estimators=100,
                                                                      n_jobs=-1,
                                                                      oob_score=False,
                                                                      random_state=100,
                                                                      verbose=0,
                                                                      warm_start=False))],
                                  flatten_transform=True, n_jobs=-1,
                                  verbose=False, voting='soft',
                                  weights=None))],
         verbose=False)

### 예측 수행 및 평가

In [ ]:
y_pred = predict_model( model, data=X_test)

# 예측 결과 샘플 2개
y_pred.head(2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,prediction_label,prediction_score
204,12.470000,18.600000,81.089996,481.899994,0.09965,0.1058,0.08005,0.03821,0.1925,0.06373,...,96.050003,677.900024,0.1426,0.2378,0.2671,0.1015,0.3014,0.08750,1,0.9130
70,18.940001,21.309999,123.599998,1130.000000,0.09009,0.1029,0.10800,0.07951,0.1582,0.05461,...,165.899994,1866.000000,0.1193,0.2336,0.2687,0.1789,0.2551,0.06589,0,0.9996

In [ ]:
# 평가 (실제정답, 예측값)
# 정확도가 동일한 부분은 체크해서 오후에 확인
accuracy_score(y_test, y_pred.prediction_label)

0.9649122807017544

# AutoML 적용 - 반자동(어느 정도 개입)

### 데이터준비(생략)

### setup() (생략)

### 모델 생성

In [ ]:
models()

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
rbfsvm,SVM - Radial Kernel,sklearn.svm._classes.SVC,False
gpc,Gaussian Process Classifier,sklearn.gaussian_process._gpc.GaussianProcessC...,False
mlp,MLP Classifier,sklearn.neural_network._multilayer_perceptron....,False
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
catboost,CatBoost Classifier,catboost.core.CatBoostClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True

In [ ]:
# 모델 6개 구성 -> 경쟁을 통해서 top 모덿 획득이 아닌 직관으로 모델 지정
# 모든 모델을 검토하지 않아도 됨 => 시간 절약, 반면에 좋은 모델은 놓칠수 있다
model_gbc = create_model('gbc', fold=5)
model_xgboost = create_model('xgboost', fold=5)
model_catboost = create_model('catboost', fold=5)
model_lightgbm = create_model('lightgbm', fold=5)
model_lr = create_model('lr', fold=5)
model_lda = create_model('lda', fold=5)

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

Processing:   0%|          | 0/4 [00:00<?, ?it/s]

### 튜닝

- 개별 모델의 성능 극대화

In [ ]:
# choose_better : 성능이 높아지는쪽으로 선택
tune_model_gbc      = tune_model(  model_gbc, fold=5, optimize='Accuracy', choose_better=True )

tune_model_xgboost  = tune_model(  model_xgboost, fold=5, optimize='Accuracy', choose_better=True )

tune_model_lightgbm = tune_model(  model_lightgbm, fold=5, optimize='Accuracy', choose_better=True )

tune_model_catboost = tune_model(  model_catboost, fold=5, optimize='Accuracy', choose_better=True )

tune_model_lr       = tune_model(  model_lr, fold=5, optimize='Accuracy', choose_better=True )

tune_model_lda      = tune_model(  model_lda, fold=5, optimize='Accuracy', choose_better=True )

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 5 folds for each of 10 candidates, totalling 50 fits

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 5 folds for each of 10 candidates, totalling 50 fits

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 5 folds for each of 10 candidates, totalling 50 fits

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 5 folds for each of 10 candidates, totalling 50 fits

Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 5 folds for each of 10 candidates, totalling 50 fits

Original model was better than the tuned model, hence it will be returned. NOTE: The display metrics are for the tuned model (not the original one).

Processing:   0%|          | 0/7 [00:00<?, ?it/s]

Fitting 5 folds for each of 10 candidates, totalling 50 fits

### 최종 후보 모델

In [ ]:
# 우의 모델 전부 사용하거나 그중 상위권만 사용등 다양한 구성 가능함
candidate_models = [
    tune_model_gbc,
    tune_model_xgboost,
    tune_model_lightgbm,
    tune_model_catboost,
    tune_model_lr,
    tune_model_lda,
]
# 의미적으로는 top_5와 a동일한 성격이므로, 이후 절차는 동일함

### 이후 절차 동일( 블랜딩, 최적모델, 예측수행 및 평가)